all:
  hosts:
    ubuntu:
      ansible_host: CHANGE_ME
      ansible_ssh_user: root
      ansible_connection: ssh
    centos:
      ansible_host: CHANGE_ME
      ansible_ssh_user: root
      ansible_connection: ssh
