- hosts: all
  become: yes
  tasks:
    - import_tasks:
        file: ubuntu.yml
      when: ansible_distribution == 'Ubuntu'
    - import_tasks:
        file: centos.yml
      when: ansible_distribution == 'CentOS'
